{
  lib,
  modulesPath,
  pkgs,
  ...
}:
let
  # Corrected EDID for the 2880x1800 panel in the Lenovo IdeaPad Pro 5 14APH8.
  # Source: https://github.com/dgroenen/lenovo-ideapad-pro-5-14-14APH8-120hz-fix
  lenovo120HzEdid =
    pkgs.runCommand "lenovo-ideapad-pro-5-14aph8-edid"
      {
        nativeBuildInputs = [ pkgs.buildPackages.xxd ];
      }
      ''
        install -d "$out/lib/firmware/edid"
        xxd -r -p ${./lenovo-14aph8-edid.hex} \
          "$out/lib/firmware/edid/lenovo-14aph8.bin"
        echo "54d2433452c7c1cf02d562a40d31d38db42a696f5ed6544439e5bf1f03e9f6de  $out/lib/firmware/edid/lenovo-14aph8.bin" \
          | sha256sum --check --strict
      '';
in
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Generic PC boot support. After installation, supplement this with hardware
  # settings generated by nixos-generate-config as needed.
  boot.initrd.systemd.enable = true;
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "ahci"
    "usb_storage"
    "sd_mod"
  ];
  # Enable early AMDGPU KMS to avoid display mode switches during
  # Wayland/Hyprland startup.
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # The panel advertises its 120 Hz DisplayID mode with an invalid checksum.
  # Load the corrected EDID before AMDGPU probes the internal display.
  boot.kernelParams = [ "drm.edid_firmware=eDP-1:edid/lenovo-14aph8.bin" ];
  boot.initrd.extraFirmwarePaths = [ "edid/lenovo-14aph8.bin" ];

  boot.refindChainloader = {
    enable = true;
    # Both ESPs are on the same SSD. Use the Windows ESP's PARTUUID so rEFInd
    # can distinguish it from the 2 GiB NixOS ESP mounted at /boot.
    windowsEfiPartuuid = "084dbc6c-e077-48f9-b6d5-ccd76d8f1d42";
  };

  # This host's local exFAT data disk. Use its filesystem UUID rather than the
  # unstable /dev/sda name, and do not block boot if the disk is unavailable.
  #fileSystems."/sda" = {
  #  device = "/dev/disk/by-uuid/6B1E-7840";
  #  fsType = "exfat";
  #  options = [
  #    "rw"
  #    "nofail"
  #    "x-systemd.device-timeout=10s"
  #    "nosuid"
  #    "nodev"
  #    "uid=1000"
  #    "gid=100"
  #    "fmask=0022"
  #    "dmask=0022"
  #    "errors=remount-ro"
  #  ];
  #};

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware = {
    enableRedistributableFirmware = true;
    firmware = [ lenovo120HzEdid ];

    # Automatically include amd-ucode in the initrd and load the microcode
    # early during boot.
    cpu.amd.updateMicrocode = lib.mkDefault true;

    # Mesa provides the user-space OpenGL and Vulkan drivers for AMDGPU.
    graphics = {
      enable = true;
      enable32Bit = true;
    };
  };
}
