{ lib, modulesPath, ... }:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Generic PC boot support. After installation, supplement this with hardware
  # settings generated by nixos-generate-config as needed.
  boot.initrd.systemd.enable = true;
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "usb_storage" "sd_mod" ];
  # Enable early AMDGPU KMS to avoid display mode switches during
  # Wayland/Hyprland startup.
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.refindChainloader = {
    enable = true;
    # Windows Boot Manager resides on a separate ESP; use its PARTUUID to
    # prevent rEFInd from selecting the wrong partition.
    windowsEfiPartuuid = "991a77db-c316-4f75-b9df-bc05e179a798";
  };

  # This host's local exFAT data disk. Use its filesystem UUID rather than the
  # unstable /dev/sda name, and do not block boot if the disk is unavailable.
  #fileSystems."/sda" = {
  #  device = "/dev/disk/by-uuid/6B1E-7840";
  #  fsType = "exfat";
  #  options = [
  #    "rw"
  #    "nofail"
  #    "x-systemd.device-timeout=10s"
  #    "nosuid"
  #    "nodev"
  #    "uid=1000"
  #    "gid=100"
  #    "fmask=0022"
  #    "dmask=0022"
  #    "errors=remount-ro"
  #  ];
  #};

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware = {
    enableRedistributableFirmware = true;

    # Automatically include amd-ucode in the initrd and load the microcode
    # early during boot.
    cpu.amd.updateMicrocode = lib.mkDefault true;

    # Mesa provides the user-space OpenGL and Vulkan drivers for AMDGPU.
    graphics = {
      enable = true;
      enable32Bit = true;
    };
  };
}
